### ISSUE TITLE
Initial pod num selection

### ISSUE THREAD

**Issue by QueJJ** [liaochan/Derm#2]
Excuse me, in the **line_fit_exp.py** file, you fixed the number of pods and adjusted the workload for model training. I wonder if different initial pod numbers selection would affect the final results of **resourceAllocation.py**.

Thank you.

**Comment by liaochan** [comment]
The `pod_num` in this file originates from one of our experimental settings, which is used to calculate the number of times each container is invoked. Logically, this is only applied during the fitting process and does not directly affect resource allocation.

**Comment by QueJJ** [comment]
Thank you for the explanation. And  I have another question.

In the **resourceAllocation.py** file, the `self.profilingWorkload` is set to 40. I wonder if this is a hyperparameter learned from the historical experience, as I noticed that the workload of the training data is 30 and 60 in the **profiling** folder.

**Comment by liaochan** [comment]
Yes, due to the limitations of TrainTicket performance, the maximum workload achievable in our cluster is approximately 120. This initial value is beneficial for accelerating the search process.

**Comment by QueJJ** [comment]
Thank you very much :)
